theme: jekyll-theme-minimal
title: Ian Taylor - Design Portfolio
description: These projects were created for no other reason than to express myself through the therapeutic & meditative exercise of intense concentration to achieve an otherwise purposeless goal.
